// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANBT9QRorA4PSZeuhcxABPd-2JDILO1dY',
    appId: '1:479136193765:web:eb5ec4e17364d00f55c80c',
    messagingSenderId: '479136193765',
    projectId: 'wirelessproject-e165f',
    authDomain: 'wirelessproject-e165f.firebaseapp.com',
    storageBucket: 'wirelessproject-e165f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcYZ0X7fNl5yiDLt7k_JU_7m90b6KMlyQ',
    appId: '1:479136193765:android:6de080644ad46ca355c80c',
    messagingSenderId: '479136193765',
    projectId: 'wirelessproject-e165f',
    storageBucket: 'wirelessproject-e165f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbm7BvRu-TZyyqovlCMGdTGIRvStOJ-Lk',
    appId: '1:479136193765:ios:78b5e02f146a52f055c80c',
    messagingSenderId: '479136193765',
    projectId: 'wirelessproject-e165f',
    storageBucket: 'wirelessproject-e165f.appspot.com',
    iosBundleId: 'com.example.homealertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbm7BvRu-TZyyqovlCMGdTGIRvStOJ-Lk',
    appId: '1:479136193765:ios:110f628fab62341a55c80c',
    messagingSenderId: '479136193765',
    projectId: 'wirelessproject-e165f',
    storageBucket: 'wirelessproject-e165f.appspot.com',
    iosBundleId: 'com.example.homealertApp.RunnerTests',
  );
}
